lista_compras = ['banana','laranja','maçã']
print(lista_compras)
['banana', 'laranja', 'maçã']
#Cada item da lista possui uma posição. Por padrão, as posições não iniciam do 1 (um) e sim do 0 (ZERO). Nos códigos seguintes temos as formas de acessar uma informação da lista.

#Para acessarmos um item da lista vamos utilizar a estrutura: nomedalista[posição].

#Buscando a posição [1]:

print(lista_compras[1])
#laranja
#Buscando a posição [0]:

print(lista_compras[0])
#Banana
#Se tentarmos buscar a posição [3] teremos um erro. Isso corre, porque não existe uma posição 3. Apenas as posições [0], [1], [2]:

print(lista_compras[3])
